FROM apache/hive:4.0.0

USER root

COPY jars/postgresql-42.6.0.jar /opt/hive/lib/postgresql-42.6.0.jar

RUN chmod 644 /opt/hive/lib/postgresql-42.6.0.jar

ENV HADOOP_CLASSPATH=/opt/hive/lib/postgresql-42.6.0.jar:/opt/hadoop/share/hadoop/tools/lib/hadoop-aws-3.3.6.jar:/opt/hadoop/share/hadoop/tools/lib/aws-java-sdk-bundle-1.12.367.jar
ENV HIVE_AUX_JARS_PATH=/opt/hive/lib/postgresql-42.6.0.jar,/opt/hadoop/share/hadoop/tools/lib/hadoop-aws-3.3.6.jar,/opt/hadoop/share/hadoop/tools/lib/aws-java-sdk-bundle-1.12.367.jar

COPY core-site.xml /opt/hive/conf/core-site.xml

USER hive
